### ISSUE TITLE
Resolving issues in the Publications

### ISSUE THREAD

**Issue by SimonGoring** [NeotomaDB/MIOMAP_Ingest#1]
All the publications are listed as citations under a single Publication tag:
 
```XML
<Publication>
  <Citation>Barnosky, A. D., 1986a, Arikareean, Hemingfordian, and Barstovian mammals from the Miocene Colter Formation, Jackson Hole, Teton County, Wyoming: Bulletin of Carnegie Museum of Natural History, v. 26, p. 1-69.</Citation>
  <Citation>Barnosky, A. D., 1986b, New species of the Miocene rodent Cupidinimus (Heteromyidae) and some evolutionary relationships within the genus: Journal of Vertebrate Paleontology, v. 6, no. 1, p. 46-64.</Citation>
</Publication>
```

Each publication should have its own Publication tags:
 
```XML
<Publication ID="1" Primary="false">
  <PublicationType>other authored</PublicationType>
  <NeotomaID>-1</NeotomaID>
  <Citation> Barnosky, A. D., 1986a, Arikareean, Hemingfordian, and Barstovian mammals from the Miocene Colter Formation, Jackson Hole, Teton County, Wyoming: Bulletin of Carnegie Museum of Natural History, v. 26, p. 1-69.</Citation>
  <Title>Barnosky, A. D., 1986a, Arikareean, Hemingfordian, and Barstovian mammals from the Miocene Colter Formation, Jackson Hole, Teton County, Wyoming: Bulletin of Carnegie Museum of Natural History, v. 26, p. 1-69</Title>
</Publication>
```

You need the ID and Primary attributes for the Publication tag. Since these pubs are not broken out into fields, you need to read them as “other authored”, so you need the PublicationType tag, You should also repeat the citation within the Citation and Title tags, with a space before the reference in the Citation tag. Finally, you should add the `<NeotomaID>-1</NeotomaID>` tag/element. 
 
These will need to be parsed in Tilia in order to upload properly. At a minimum the authors and year will need to be parsed out:
 
```XML
<Publication ID="2" Primary="false">
  <PublicationType>other authored</PublicationType>
  <NeotomaID>-1</NeotomaID>
  <PublicationYear>1986</PublicationYear>
  <Citation>Barnosky, A.D. 1986. Arikareean, Hemingfordian, and Barstovian mammals from the Miocene Colter Formation, Jackson Hole, Teton County, Wyoming: Bulletin of Carnegie Museum of Natural History, v. 26, p. 1-69.</Citation>
  <Authors>
    <Author>
      <Contact ID="1"/>
      <LastName>Barnosky</LastName>
      <Initials>A.D.</Initials>
    </Author>
  </Authors>
  <Title>Arikareean, Hemingfordian, and Barstovian mammals from the Miocene Colter Formation, Jackson Hole, Teton County, Wyoming: Bulletin of Carnegie Museum of Natural History, v. 26, p. 1-69</Title>
</Publication>
```

Note that `<Contact ID="1"/>` refers to the ID under Contacts in the Tilia file, i.e. the ID is local to the file:

```XML
<Contacts>
                <Contact ID="1">
                                <NeotomaContactID>-1</NeotomaContactID>
                                <NeotomaAliasID>0</NeotomaAliasID>
                                <FullContactName>Barnosky, A.D.</FullContactName>
                                <ShortContactName>Barnosky, A.D.</ShortContactName>
                                <FamilyName>Barnosky</FamilyName>
                                <GivenNames>A.D.</GivenNames>
                                <LeadingInitials>A.D.</LeadingInitials>
                </Contact>
</Contacts>
```

**Comment by DrPronghorn** [comment]
It may be possible to save a great deal of coding here, because every publication is listed in an EndNote file on the MIOMAP website, and that EndNote file also includes the BibNumber value from the SQL database. We should be able to read those data into a df in R and then merge the values into the publications block, so we don't have to write a script to pull apart the formatted publications.

**Comment by SimonGoring** [comment]
@DrPronghorn, Can you export the EndNote file to something like BibTex or some text representation and add it to the repository?  Then we can link to it directly from the script.  I wasn't really looking forward to parsing out the publication data :)

**Comment by SimonGoring** [comment]
@DrPronghorn Is this all sorted now?  If it is I'd like to close this issue.

**Comment by DrPronghorn** [comment]
We can close this issue.
